# Generated by Django 5.0.6 on 2024-06-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=16)),
                ('product_priority', models.IntegerField(default=1)),
                ('product_type', models.IntegerField(default=1)),
                ('product_info', models.CharField(max_length=256)),
            ],
        ),
    ]
