class NextNode:
    FIX = "问题修复"
    CLASSIFY = "问题分类"
    CHAT = "闲聊经理"
    INTENT = "意图确认"
    GATHER = "信息收集"
    CONFIRM = "信息确认"
    RECOMMEND = "产品推荐"
    CONVERSION = "客户转化"
    QA = "产品解答专家"
    FINISH = "FINISH"
